export var keyMapping = {
    registration_number: 'Registration Number',
    status: 'Status',
    status_date: 'Status Date',
    type: 'Type',
    use: 'Use',
    axels: 'Axels',
    cerb_weight: 'Cerb Weight KG',
    chassis_type: 'Chassis Type',
    color: 'Color',
    coupling: 'Coupling',
    doors: 'Doors',
    engine_cylinders: 'Engine Cylinders',
    engine_power: 'Engine Power HP',
    engine_volume: 'Engine Volume CC',
    first_registration: 'First Registration',
    fuel_type: 'Fuel Type',
    hybrid_type: 'Hybrid Type',
    is_hybrid: 'Is Hybrid',
    is_leasing: 'Is Leased',
    leasing_from: 'Leasing From',
    leasing_to: 'Leasing To',
    make: 'Make',
    model: 'Model',
    model_type: 'Model Type',
    model_year: 'Model Year',
    mot_info: 'Mot Info',
    own_weight: 'Car Weight KG',
    pulling_axels: 'Pulling Axels',
    registration_zipcode: 'Registration Zipcode',
    seats: 'Seats',
    total_weight: 'Total Weight KG',
    trailer_maxweight_nobrakes: 'Trailer Max Weight No Brakes',
    trailer_maxweight_withbrakes: 'Trailer Max Weight With Brakes',
    variant: 'Variant',
    vehicle_id: 'Vehicle ID',
    vin: 'VIN'
  };